spring.application.name=Fortissimo
spring.config.import=optional:configtree:/run/secrets/
sdb.websocketSendRateLimit=500
sdb.websocketMessageSizeLimit=1048576

# 以下機密情報につき空欄
fortissimo.clientId=
fortissimo.clientSecret=
fortissimo.redirectUri=
sdb.botToken=
sdb.intents=